# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bd071c08bcf05bf7f5ab88e2354c9c360422e3a51173ee3f50f4cae9e20a43dae9ab8d13d65ec57ed16ce057f1a3f065f6344edd2e869e73aa3b13e92fac6e5

test:
  secret_key_base: 2959db8de6efc1f36332dd618932c9f58a15c9637142d5dad5d683b332a332ca4a1177344ec7698c7a7a093671886dcc4a779312370b1c689f8f41f911857ded

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
